/**
 * contracts/index.ts — 平台级共享类型
 */
export type { ModuleCatalog, ModuleCatalogEntry, ModuleEntryPath, ModuleLock, ModuleRuntimeState } from "./module.js";
export { UI_DOCUMENT_FORMAT_VERSION } from "./ui-document.js";
export type {
  UiActionDefinition,
  UiButtonNode,
  UiConfirmDefinition,
  UiDataSource,
  UiDividerNode,
  UiDropdownNode,
  UiDropdownOption,
  UiEachNode,
  UiEffect,
  UiEntryDefinition,
  UiExpression,
  UiExpressionOperator,
  UiFeatureDocument,
  UiHeaderNode,
  UiImageNode,
  UiInfoNode,
  UiJsonValue,
  UiNode,
  UiNodeBase,
  UiParamDefinition,
  UiPresentation,
  UiProject,
  UiReferenceRoot,
  UiScreenDocument,
  UiScreenReference,
  UiServiceCall,
  UiSliderNode,
  UiSpacerNode,
  UiStateDefinition,
  UiTextFieldNode,
  UiTextNode,
  UiToggleNode,
  UiTone,
  UiTrigger,
  UiWhenNode,
} from "./ui-document.js";
